---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: hello-world
spec:
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - image: gpaul/hello-world@sha256:7efe38b18679d2514fb1961f7d389e0172f2d10f81f21d18859528f82a671ade
        name: hello-world
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: hello-world
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    certmanager.k8s.io/issuer: letsencrypt-issuer
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/auth-response-headers: X-Forwarded-User
    traefik.ingress.kubernetes.io/auth-type: forward
    traefik.ingress.kubernetes.io/auth-url: http://traefik-forward-auth-kubeaddons.kubeaddons.svc.cluster.local:4181/
    traefik.ingress.kubernetes.io/rule-type: PathPrefixStrip
  generation: 1
  labels:
    app.kubernetes.io/instance: hello-world
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: hello-world
  name: hello-world
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: hello-world
          servicePort: 80
        path: /hello-world

